import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";

const meriwether = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--Merriweather",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cn(meriwether.variable)}`}
        style={{ fontFamily: "var(--Merriweather)" }}
      >
        <Toaster position="top-center" />
        <main>{children}</main>
      </body>
    </html>
  );
}
