import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "react-hot-toast";
import LoginPage from "./login/page";

const meriwether = Merriweather({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--Merriweather",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500"],
  variable: "--Inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cn(inter.variable)}`}
        style={{ fontFamily: "var(--Inter)" }}
      >
        <Toaster position="top-center" />
        <div>
          {/* <LoginPage /> */}
          <div>
            <main>{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
